name: Python CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Check
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
        pip install fastapi uvicorn python-dotenv pylint

    - name: Run Pylint
      run: |
        python -m pylint app/ --exit-zero

    - name: Test Basic Imports
      run: |
        echo "Testing essential imports..."
        python -c "from app.main import app; print('✅ FastAPI app imported successfully')"
        
    - name: Test Optional Imports
      continue-on-error: true
      run: |
        echo "Testing optional imports..."
        python -c "from app.schemas import Livro; print('✅ Schemas imported successfully')" || echo "⚠️ Schemas not available yet"
        python -c "from app.crud import crud_livros; print('✅ CRUD imported successfully')" || echo "⚠️ CRUD not available yet"
        python -c "from app.database import livros_db; print('✅ Database imported successfully')" || echo "⚠️ Database not available yet"