name: Python CI Pipeline

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    name: Code Quality Check
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        cache: 'pip'

    - name: Install Python dependencies
      run: |
        pip install fastapi uvicorn python-dotenv
        pip install pylint

    - name: List installed packages
      run: |
        pip list

    - name: Run Pylint with module approach
      run: |
        python -m pylint app/ --exit-zero --output-format=colorized

    - name: Basic functionality test
      run: |
        echo "Testing Python imports..."
        python -c "
        try:
            from app.main import app
            from app.schemas import Livro
            from app.crud import crud_livros
            from app.database import livros_db
            print('✅ All imports successful!')
            print(f'📚 Found {len(livros_db)} books in database')
        except Exception as e:
            print(f'❌ Import error: {e}')
            exit(1)
        "