name: Python CI

on:
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Check code quality with Pylint
      run: |
        pylint app/ --exit-zero
        
    - name: Verify all modules can be imported
      run: |
        python -c "import app.main, app.schemas, app.crud, app.database; print('✅ All imports successful!')"